language: java
jdk:
  - oraclejdk8
install:
  - npm install -g jspm@beta
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - build/jspm/static/jspm_packages/
