server:
  port: 8080
  undertow:
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.jmailen: 'INFO'
    org.springframework: 'INFO'
