server:
  port: 8002
  undertow:
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
  error:
    whitelabel:
      enabled: true

logging:
  level:
    org.jmailen: 'DEBUG'
    org.springframework: 'INFO'
